<a href="https://colab.research.google.com/github/dominicbarasa/Artificial-Intelligence-/blob/main/Week_3_Assignment_ML_Workflow_Concrete_Strength.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Week 3 Assignment | Designing Your Machine Learning Workflow

**Name:** Dominic Barasa  
**Email:** dbarasa195@gmail.com  

**Course Project:** Prediction of Concrete Compressive Strength Using Machine Learning

## 1. Project Problem and Intended AI/ML Outcome

### Project Problem

I would like to investigate the prediction of concrete compressive strength using artificial intelligence and machine learning.

The project will explore whether concrete compressive strength can be predicted from concrete mix characteristics and curing age, including cement content, water content, aggregate quantities, admixtures, and age at testing.

### Intended AI/ML Outcome

The intended outcome is to develop a machine learning system that can predict the compressive strength of concrete in MPa from the available concrete mix and age information.

The system could potentially support concrete mix design, quality control, and engineering decision-making by providing an estimated compressive strength before or alongside conventional laboratory testing.

## 2. Data Required

To investigate the problem, I need historical concrete mix and laboratory testing data.

The useful information includes:

- Cement content (kg/m³)
- Blast furnace slag content (kg/m³)
- Fly ash content (kg/m³)
- Water content (kg/m³)
- Superplasticizer content (kg/m³)
- Coarse aggregate content (kg/m³)
- Fine aggregate content (kg/m³)
- Age of concrete at testing (days)
- Measured concrete compressive strength (MPa)

The first eight variables will be considered potential input features, while the measured concrete compressive strength will be the target variable that the machine learning system will attempt to predict.

In [1]:
import pandas as pd

# Load the concrete compressive strength dataset
url = "https://raw.githubusercontent.com/HansenHan/ML_UCI_Concrete_Compressive_Strength/main/Concrete_Data.csv"

df = pd.read_csv(url)

# Display the first five rows
df.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Concrete compressive strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

## 3. Dataset

The dataset used for this project is the Concrete Compressive Strength dataset from the UCI Machine Learning Repository.

The dataset contains 1,030 observations and 9 variables. Eight variables describe the concrete mixture and curing age, while the ninth variable is the measured concrete compressive strength.

The dataset is suitable for a regression problem because the target variable, concrete compressive strength, is a continuous numerical value measured in MPa.

In [2]:
# Display the first 10 observations
df.head(10)

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Concrete compressive strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30
5,266.0,114.0,0.0,228.0,0.0,932.0,670.0,90,47.03
6,380.0,95.0,0.0,228.0,0.0,932.0,594.0,365,43.70
7,380.0,95.0,0.0,228.0,0.0,932.0,594.0,28,36.45
8,266.0,114.0,0.0,228.0,0.0,932.0,670.0,28,45.85
9,475.0,0.0,0.0,228.0,0.0,932.0,594.0,28,39.29

In [3]:
# Display the number of rows and columns
print("Dataset shape:", df.shape)

Dataset shape: (1030, 9)

In [4]:
# Display the names of all variables
print(df.columns)

Index(['Cement', 'Blast Furnace Slag', 'Fly Ash', 'Water', 'Superplasticizer',
       'Coarse Aggregate', 'Fine Aggregate', 'Age',
       'Concrete compressive strength'],
      dtype='object')

## 4. Potential Input Features

The potential input features for the machine learning model are:

1. Cement
2. Blast Furnace Slag
3. Fly Ash
4. Water
5. Superplasticizer
6. Coarse Aggregate
7. Fine Aggregate
8. Age

These variables describe the composition of the concrete mixture and the age of the concrete when its strength was measured.

### Target Variable

The target variable is:

**Concrete compressive strength**

The target is measured in **MPa (megapascals)**.

The machine learning system will use the eight input features to predict this continuous numerical value.

In [7]:
# Define the input features
features = [
    "Cement",
    "Blast Furnace Slag",
    "Fly Ash",
    "Water",
    "Superplasticizer",
    "Coarse Aggregate",
    "Fine Aggregate",
    "Age"
]

# Define the target
target = "Concrete compressive strength"

print("Features:")
for feature in features:
    print("-", feature)

print("\nTarget:")
print("-", target)

Features:
- Cement
- Blast Furnace Slag
- Fly Ash
- Water
- Superplasticizer
- Coarse Aggregate
- Fine Aggregate
- Age

Target:
- Concrete compressive strength

## 5. Proposed Machine Learning Workflow

The proposed workflow is:

**Problem Definition**  
↓  
**Collect / Obtain Concrete Dataset**  
↓  
**Explore and Understand the Data**  
↓  
**Clean and Prepare the Data**  
↓  
**Select Features and Target**  
↓  
**Split Data into Training and Testing Sets**  
↓  
**Train Machine Learning Regression Model**  
↓  
**Evaluate Model Performance**  
↓  
**Interpret Results**  
↓  
**Predict Concrete Compressive Strength**

## 5. Proposed Machine Learning Workflow

```text
┌──────────────────────────────┐
│      Define the Problem      │
│ Predict concrete strength    │
└──────────────┬───────────────┘
               ↓
┌──────────────────────────────┐
│       Obtain Dataset         │
│ Concrete mix + age + strength│
└──────────────┬───────────────┘
               ↓
┌──────────────────────────────┐
│     Explore the Dataset      │
│ Inspect variables and data   │
└──────────────┬───────────────┘
               ↓
┌──────────────────────────────┐
│    Clean & Prepare Data      │
│ Check missing values/errors  │
└──────────────┬───────────────┘
               ↓
┌──────────────────────────────┐
│ Select Features and Target   │
│ 8 Features → 1 Target       │
└──────────────┬───────────────┘
               ↓
┌──────────────────────────────┐
│     Split the Dataset        │
│ Training Data + Testing Data │
└──────────────┬───────────────┘
               ↓
┌──────────────────────────────┐
│     Train ML Regression      │
│            Model             │
└──────────────┬───────────────┘
               ↓
┌──────────────────────────────┐
│     Evaluate the Model       │
│ Compare predictions with     │
│ measured strength            │
└──────────────┬───────────────┘
               ↓
┌──────────────────────────────┐
│      Final Prediction        │
│ Predict compressive strength │
│            (MPa)             │
└──────────────────────────────┘